name: Build Super Modyssey Loader

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Update repo
      run: |
        git submodule update --init --recursive
        
    - name: Build
      run: |
        make
        
    - uses: actions/upload-artifact@master
      with:
        name: Super Modyssey Loader
        path: |
          SuperModysseyLoader/SuperModysseyLoader.elf
          SuperModysseyLoader/SuperModysseyLoader.nacp
          SuperModysseyLoader/SuperModysseyLoader.nro